### ISSUE TITLE
[Request] TrueNAS ready docker-compose

### ISSUE THREAD

**Issue by Vysp3r** [TeamPiped/Piped-Docker#22]
It would be nice to have a docker-compose file ready to use for TrueNAS for a easier setup. Otherwise I'm testing a way to make this work on TrueNAS. If I find a way I will share it.

**Comment by anzerr** [comment]
Truenas scale uses helm for it application deployment. There's a project called [truecharts](https://github.com/truecharts/charts) that has unofficial charts, that's the project that should be looked at. The only problem I can see is it uses a dependency system so  it would cover nginx/caddy and postgres but I don't know what it look like for the 3 microservices pipedfrontend, ytproxy and piped.

**Comment by kubo6472** [comment]
https://github.com/TeamPiped/Piped-Kubernetes :O
