### ISSUE TITLE
Why use nginx in Caddy configuration?

### ISSUE THREAD

**Issue by eqiowtj** [TeamPiped/Piped-Docker#30]
In the Caddy AIO script linked here: https://piped-docs.kavin.rocks/docs/self-hosting/
The backend is reversed proxied by nginx, then Caddy.
Is there any particular reason to put nginx in the middle?

**Comment by FireMasterK** [comment]
Yes, because afaik caddy can't cache as a reverse proxy. (We'll been a build with xcaddy I think)

**Comment by eqiowtj** [comment]
Thank you for the explanation!
