### ISSUE TITLE
Using other proxy instances

### ISSUE THREAD

**Issue by binaryben** [TeamPiped/Piped-Docker#31]
I'm a bit concerned about bandwidth use.

It seems technically possible[^test] to run just the frontend image without command to change the instance URLs. I'm assuming the proxy service will be the biggest bandwidth consumer.

Can we set up a piped backend service using a proxy of a public instance? (i.e., use `pipedproxy-yyz.kavin.rocks` as the URL for the `PROXY_HOSTNAME` value - this is what I saw in the network tab on the kavin.rocks instance)

My motivation is that I'd prefer to host the account/subscription data, etc for my private instance. But I'm not really fussed if another instance operator knows which videos have been watched.

[^test]: I've only tested to the point of running the `1337kavin/piped-frontend` container locally and using `entrypoint: ash -c '/docker-entrypoint.sh && nginx -g "daemon off;"'` as the command. It seems to work as expected (not too surprising since it's a Vue app) and plays videos - I just haven't tested logging in yet

**Comment by Bnyro** [comment]
> Can we set up a piped backend service using a proxy of a public instance? (i.e., use pipedproxy-yyz.kavin.rocks as the URL for the PROXY_HOSTNAME value - this is what I saw in the network tab on the kavin.rocks instance)
>
No, that's not officially supported.

I would recommend keeping your instance private and choose your instance as the `authentication instance` in the settings (both Piped and LibreTube support it), and use any other instance as the default instance.

That way your subscriptions and playlists will be synced with the authentication API, but everything else like playing videos will use the api/proxy of an other instance.
