### ISSUE TITLE
Nginx can't resolve hostname because of hardcoded dns resolver in nginx.conf

### ISSUE THREAD

**Issue by nyarau** [TeamPiped/Piped-Docker#34]
Currently a hard coded resolver address `127.0.0.11` is set in [`nginx.conf`](https://github.com/TeamPiped/Piped-Docker/blob/49b98cbeb3a1d8042ccd384b81976793bcd06a53/template/nginx.conf#L30)
~~It works in typical Docker setup, however it fails in setups using Podman with an explicit IPAM~~
It works with Docker, but fails with Podman where dns is `10.89.0.1` by default.
```
piped-nginx     | 2023/10/05 09:33:20 [error] 31#31: recv() failed (111: Connection refused) while resolving, resolver: 127.0.0.11:53
piped-nginx     | 2023/10/05 09:33:24 [error] 30#30: *1 piped could not be resolved (110: Operation timed out), client: 10.11.8.1, server: piped-api.example.com, request: "GET /channel/UCBR8-60-B28hp2BmDPdntcQ HTTP/1.1", host: "piped-api.example.com"
```
---
Referring to https://stackoverflow.com/a/31864024 , I removed `resolver` line in `nginx.conf` and used the following config as `pipedapi.conf`, which indeed fixed the issue.
```nginx
proxy_cache_path /tmp/pipedapi_cache levels=1:2 keys_zone=pipedapi:4m max_size=2g inactive=60m use_temp_path=off;

upstream pipedapi {
    server piped:8080;
}
server {
    listen 80;
    server_name piped-api.example.com;

    location / {
        proxy_cache pipedapi;
        proxy_pass http://pipedapi;
        proxy_http_version 1.1;
        proxy_set_header Connection "keep-alive";
    }
}
```

**Comment by Bnyro** [comment]
I think that's a reasonable change, can you please create a pull request?
