### ISSUE TITLE
Is the install compatible with ipv6 only instances ?

### ISSUE THREAD

**Issue by tarbib** [TeamPiped/Piped-Docker#36]
Hello,

Here is my DNS records :
![image](https://github.com/TeamPiped/Piped-Docker/assets/2255433/bd53cd9e-c2ce-4815-b3b1-66e4b6edb3de)
I've run ./configure-instance.sh
I get this error:
![image](https://github.com/TeamPiped/Piped-Docker/assets/2255433/2e027219-7a7f-419b-8c21-a85104763762)

Additional infos from https://ready.chair6.net/
![image](https://github.com/TeamPiped/Piped-Docker/assets/2255433/b5fded3a-96f6-493a-b1ee-da9995da2118)

I was wondering can Piped with Docker work with ipv6 only servers?

Thanks

**Comment by tarbib** [comment]
In the logs it seems that letsencrypt servers are not reachable:

`caddy           | {"level":"error","ts":1704221056.9808023,"logger":"tls.obtain","msg":"could not get certificate from issuer","identifier":"MYDOMAIN.io","issuer":"acme-v02.api.letsencrypt.org-directory","error":"registering account [] with server: provisioning client: performing request: Get \"https://acme-staging-v02.api.letsencrypt.org/directory\": dial tcp 172.65.46.172:443: connect: network is unreachable"}
`

On the other hand it seems supported:
https://letsencrypt.org/docs/ipv6-support/

**Comment by Bnyro** [comment]
Did you try appending
```
networks:
  default:
    enable_ipv6: true
    ipam:
      config:
        - subnet: 2001:db8::/112
```
to the end of `docker-compose.yml`? Enabling IPv6 is described at the bottom of https://docs.piped.video/docs/self-hosting/ (IPv6 rotator section).
