### ISSUE TITLE
how to run it without caddy or nginx?

### ISSUE THREAD

**Issue by rachmadaniHaryono** [TeamPiped/Piped-Docker#6]
on doc https://piped-docs.kavin.rocks/docs/self-hosting/ there is only example to run it with reverse proxy.

configure-instance will raise error if i enter empty string for `reverseproxy`

or is it out of this project scope?

**Comment by FireMasterK** [comment]
What's the rationale behind this? This has been done specifically for your convenience, I don't understand why you would want to do this.

**Comment by rachmadaniHaryono** [comment]
> What's the rationale behind this? ...I don't understand why you would want to do this.

easier installation. as comparison with invidious you can just copy the compose file and run docker compose with the file

i'm beginner in docker and have no experience with nginx or caddy. i just want to try to run piped locally

> This has been done specifically for your convenience

if  it is special case and out of scope from this project, this issue can be closed

**Comment by FireMasterK** [comment]
> i just want to try to run piped locally

You shouldn't be doing this, Piped wasn't intended for that!

The reason being pubsub wouldn't work, and managing 3 different services/ports will be a pain.

Unlike Invidious which is monolithic, Piped requires 3-5 containers for everything, which makes things significantly difficult to run without hostnames, this is hence why there is a script for normal server installations!

I'll close this as you requested.
